---
abstract: 'yet another flock package'
author:
  - 'Pavel Shaydo, C<< <zwon at cpan.org> >>'
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  File::Slurp: 0
  Path::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Flock-Tiny
no_index:
  directory:
    - inc
    - t
requires:
  parent: 0
  perl: 5.8.0
resources:
  bugtracker: http://github.com/trinitum/perl-File-Flock-Tiny/issues
  homepage: http://github.com/trinitum/perl-File-Flock-Tiny
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-File-Flock-Tiny
version: 0.06
